name: Build Blue Nine Access (APK)

on:
  workflow_dispatch:
  push: { branches: [ main, master ] }

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROJECT_DIR: BlueNineAccess_Full_Buildable/Blue Nine Access

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Ensure Gradle wrapper exists
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          build-root-directory: ${{ env.PROJECT_DIR }}
          arguments: wrapper

      - name: List Gradle projects (diagnostics)
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          chmod +x ./gradlew
          ./gradlew projects

      - name: Build debug APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          ./gradlew :app:assembleDebug --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: bluenineaccess-debug-apk
          path: ${{ env.PROJECT_DIR }}/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
